name: recipebook
description: All recipes in one place
publish_to: 'none'
version: 1.0.0+1

environment:
    sdk: ">=2.12.0 <3.0.0"

dependencies:
    beamer: ^0.14.1 # навигация
    cached_network_image: ^3.1.0
    cupertino_icons: ^1.0.3
    dio: ^4.0.0 # взаимодействие с API
    dotted_border: ^2.0.0+1
    file_picker: ^4.0.2
    fish_redux: ^0.3.7
    flutter:
        sdk: flutter
    flutter_svg: ^0.22.0
    get_it: ^7.2.0
    google_fonts: ^2.1.0
    json_annotation: ^4.1.0
    provider: ^6.0.0
    url_launcher: ^6.0.10 # запуск внешних ссылок
    url_strategy: ^0.2.0 # убирает '#' в url

dev_dependencies:
    build_runner: ^2.1.2
    json_serializable: ^5.0.0
    lint: ^1.7.2

flutter:
    uses-material-design: true
    assets:
        - assets/icons/
        - assets/images/
        - google_fonts/

